#include <iostream>
#include "socket_server.hpp"
#include "message_handler.hpp"
#include "socket_client.hpp"
#include "../protocol/generated/s2c_generated.h"

using namespace abby;

int main(int argc,char** argv){
    std::cout << "start main func." << std::endl;
    try {
        message_handler handler;
        socket_server server_instance;

        server_instance.set_handler(std::bind(&message_handler::on_message,&handler,std::placeholders::_1));
        server_instance.start(9002);

        sleep(1);

        std::thread([&]{
             while (1)
            {
                std::cout << "sleep 1" << std::endl;

                flatbuffers::FlatBufferBuilder builder;
                auto entry = CreateServerA(builder,2.30,builder.CreateString("a"));
                auto serverData = CreateServerData(builder,abby::ServerType_ServerA,
                    abby::ServerField::ServerField_ServerA,entry.Union());
                builder.Finish(serverData);
                uint8_t *buf = builder.GetBufferPointer();
                std::uint32_t bodySize = builder.GetSize();


                // Autogenerated class from table Monster.
                // MonsterT monsterobj;

                // // Deserialize from buffer into object.
                // GetMonster(flatbuffer)->UnPackTo(&monsterobj);

                // // Update object directly like a C++ class instance.
                // cout << monsterobj->name;  // This is now a std::string!
                // monsterobj->name = "Bob";  // Change the name.

                // // Serialize into new flatbuffer.
                // FlatBufferBuilder fbb;
                // fbb.Finish(Monster::Pack(fbb, &monsterobj));

                /*
                flatbuffers::FlatBufferBuilder builder;
                ServerAT s_a_obj;
                s_a_obj.name = "a";
                s_a_obj.price = 2.30;
                builder.Finish(ServerA::Pack(builder,&s_a_obj)); 
                std::cout << "buf size:" << bodySize << std::endl;
                */
                /*
                uint8_t *buf = builder.GetBufferPointer();
                std::uint32_t bodySize = builder.GetSize();
                uint8_t *data = new uint8_t[bodySize];
                memcpy(data,buf,bodySize);

                auto desData = GetServerData((const uint8_t*)data);
                std::cout << "type:" << desData->type() << std::endl;
                switch (desData->type()) // union自带type
                {
                    case ServerType_ServerA:
                    {
                        auto quote = reinterpret_cast<const abby::ServerA *>(desData->message());
                        std::cout << "name: " << quote->name()->c_str() << ", price: " << quote->price();
                        break;
                    }
                    case ServerType_ServerB:
                    {
                        auto quote = reinterpret_cast<const abby::ServerB *>(desData->message());
                        std::cout << "name: " << quote->name()->c_str() << ", age: " << quote->age();
                        break;
                    }
                    case ServerType_ServerC:
                    {
                        auto quote = reinterpret_cast<const abby::ServerC *>(desData->message());
                        std::cout << "name: " << quote->name()->c_str() << ", weight: " << quote->weight();
                        break;
                    }
                    default:
                    {
                        std::cout << "min:" <<   abby::ServerType::ServerType_MIN << std::endl;
                        std::cout << "max:" <<   abby::ServerType::ServerType_MAX << std::endl;
                        std::cout << "undefined type." << desData->type() << std::endl;
                        break;
                    }
                }

                delete data;
                */

                
                uint8_t *data = new uint8_t[bodySize+4];
                memcpy(data,&bodySize,4);
                memcpy(data+4,buf,bodySize);
                for (size_t i = 0; i < bodySize+4; i++)
                {
                    printf("%02X ",data[i]);
                }
                printf("\n");
                server_instance.send(data,bodySize+4);

                delete data;
                
                sleep(1);
            }
        }).detach();

        socket_client client;
        client.start();

        

        server_instance.stop();

    } catch (websocketpp::exception const & e) {
        std::cout << e.what() << std::endl;
    }
    return 0;
}